### ISSUE TITLE
Tanin wo Yosetsukenai Buaisouna Joshi ni Sekkyou shitara, Mechakucha Natsukareta

### ISSUE THREAD

**Issue by installkode** [LNReader/lnreader-sources#552] opened 2023-07-27 02:37 UTC
### Source information

SakuraNovel

### Steps to reproduce

Empty chapters

### Expected behavior

Please repair quickly 

### Actual behavior

No improvement is expected

### LNReader version

1.1.16

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-07-27 02:39
Duplicate of #522

**Closed by rajarsheechatterjee** 2023-07-27 02:39 UTC
Labels: Bug
