### ISSUE TITLE
I can't export an epub

### ISSUE THREAD

**Issue by Jaj29** [LNReader/lnreader-sources#684] opened 2024-01-10 15:57 UTC
### Source information

Agitoon

### Steps to reproduce

![Screenshot_2024-01-10-17-53-24-29_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/144594100/555a28f9-1433-461b-9088-d94ed5278e47) 

### Expected behavior

To export the epub as always

### Actual behavior

It gives me this message "Error: Resource ID #0x0

### LNReader version

1.1.18.

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-01-11 15:20
Duplicate of https://github.com/LNReader/lnreader/issues/820

**Closed by rajarsheechatterjee** 2024-01-11 15:20 UTC
Labels: Bug
