### ISSUE TITLE
Tunovelaligera: fix chapters

### ISSUE THREAD

**Issue by christmovies** [LNReader/lnreader-sources#626] opened 2023-10-29 06:09 UTC
### Source information

Tunovelaligera l

### Steps to reproduce

Enter extension
Enter novel 

### Expected behavior

They must upload more than 1000 chapters

### Actual behavior

does not load, 1 in every hundred loads but less than 20 chapters.

https://tunovelaligera.com/

### LNReader version

1.1.18

### Android version

13

### Other details

please fix it, 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-10-29 06:33
Duplicate of #595

**Closed by rajarsheechatterjee** 2023-10-29 06:33 UTC
Labels: Bug
