### ISSUE TITLE
FastNovel not working

### ISSUE THREAD

**Issue by MonomoySama** [LNReader/lnreader-sources#565] opened 2023-08-14 06:47 UTC
### Source information

FastNovel

### Steps to reproduce

1. Opening the source
2. Clicking on any novel or webview of that

### Expected behavior

If this source exists in app it should work right?

### Actual behavior

Whenever i open the source, only some of the novel covers load and when i open those novels it says " NOT NULL constraint failed: novels.novelName (code 1299 SQLITE_CONSTRAINT_NOTNULL) "
And opening the source in webview says " Error 1015 you are being rate limited. The owner of the site has temporarily banned you from accesing the site"

### LNReader version

1.1.17

### Android version

Android 10

### Other details

All the novels i read are from this site coz it updates very fast. Now that its having problem i can't read anything and some of the novels i read couldn't be found in other sources so please fix it ASAP if possible 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-08-14 07:37
Duplicate of #558

**Closed by rajarsheechatterjee** 2023-08-14 07:37 UTC
Labels: Bug

**Comment by MonomoySama** [comment] 2023-08-14 09:22
> Duplicate of #558

Will it take time to fix? It's been weeks but still not fixed

**Comment by rajarsheechatterjee** [comment] 2023-08-14 09:35
> Wait until someone wants to work on it.

You could either wait for someone to fix or or feel free to contribute and fix it yourself.

**Comment by MonomoySama** [comment] 2023-08-14 16:10
> > Will it take time to fix? It's been weeks but still not fixed
> 
> You could either wait for someone to fix it or or feel free to contribute and fix it yourself.

There's a problem in the app, so the user places a complaint and you say the user to fix the problem themselves? And until someone WANTS to fix the problem we have to wait? Wth

**Comment by rajarsheechatterjee** [comment] 2023-08-14 17:00
> There's a problem in the app, so the user places a complaint and you tell the user to fix the problem themselves? And until someone WANTS to fix the problem we have to wait? Wth

It's an open source project. No one gets paid to maintain it and neither are you paying to use the app. So as previously said could either wait for someone to fix it or or feel free to contribute and fix it yourself.

**Comment by SkillGG** [comment] 2023-08-14 20:22
There is an alternative. Just remove the extension. No extension = no issue. It'll just be piled at the end of the long line of the sources yet to be implemented.
