### ISSUE TITLE
sunovels

### ISSUE THREAD

**Issue by Aternal00** [LNReader/lnreader-sources#132] opened 2021-12-13 20:48 UTC
### Source name

sunovels

### Source link

https://sunovels.com/

### Language

Arabic

### Other details

just add this one it will help alot !!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2021-12-26 05:47
Duplicate of #130

**Closed by rajarsheechatterjee** 2021-12-26 05:47 UTC
Labels: Source request
