### ISSUE TITLE
No results found 

### ISSUE THREAD

**Issue by modiabofficial** [LNReader/lnreader-sources#343] opened 2022-07-26 23:28 UTC
Some sources don't work for example:
1.ArNovel
2.TeamXNovel doesn't work well 
3.KolNovel.

**Comment by rajarsheechatterjee** [comment] 2022-07-28 01:12
Arnovel and TeamXNovel works fine for me. Maintaining sources of other languages is difficult for me so feel free to fix them or wait for someone to fix them. KolNovel - Duplicate of #146

**Closed by rajarsheechatterjee** 2022-07-28 01:12 UTC

**Comment by modiabofficial** [comment] 2022-07-31 17:23
How to fix it?
