### ISSUE TITLE
Kolnovel no results problem

### ISSUE THREAD

**Issue by Sidahmedreb** [LNReader/lnreader-sources#213] opened 2022-04-30 11:09 UTC
### Source information

Kolnovel

### Steps to reproduce

1.
![20220430_120302](https://user-images.githubusercontent.com/104678301/166102830-a0055d33-ab38-417c-8451-12e8877cfa99.jpg)
2.
Kolnovel
3.
![20220430_120246](https://user-images.githubusercontent.com/104678301/166102873-2230693f-16b4-4acb-af98-61cd67c6c1ed.jpg)
No results found

### Expected behavior

The novels had to appear

### Actual behavior

But I have a problem and it said no results found

### LNReader version

1.1.8

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.8](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2022-04-30 12:21
Duplicate of #146

**Closed by rajarsheechatterjee** 2022-04-30 12:21 UTC
Labels: bug
