### ISSUE TITLE
kolnovel : Source bug fix

### ISSUE THREAD

**Issue by yemenihandsome** [LNReader/lnreader-sources#382] opened 2022-09-04 08:26 UTC
### Source information

Kolnovel

### Steps to reproduce

Log in to the source Failure appears, and novels do not appear .
In some applications of other novels in which this source is working, an example of this is an application IReader. 

### Expected behavior

Stories must appear 

### Actual behavior

No novels appear

### LNReader version

1.1.13

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2022-12-09 04:20
Duplicate of #146

**Closed by rajarsheechatterjee** 2022-12-09 04:20 UTC
Labels: Bug
