### ISSUE TITLE
Request new novel source 

### ISSUE THREAD

**Issue by darkpewds6969** [LNReader/lnreader-sources#190] opened 2022-03-24 11:07 UTC
### Source name

Novelhi

### Source link

https://novelhi.com/

### Language

English 

### Other details

Good Chinese novel translation

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2022-03-24 12:00
Duplicate of #124

**Closed by rajarsheechatterjee** 2022-03-24 12:00 UTC
Labels: source request
