### ISSUE TITLE
ReaperScans No results 

### ISSUE THREAD

**Issue by MoeTZin** [LNReader/lnreader-sources#477] opened 2023-04-09 07:02 UTC
### Source information

ReaperScans

### Steps to reproduce

Browse>ReaperScans>No results 

### Expected behavior

Should be showing the novel list

### Actual behavior

Showing blank screen "no results"
![Screenshot_2023-04-09-13-19-41-617_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/72650513/230759158-c7b701dd-f191-4597-a440-1e8bd1666cde.jpg)

### LNReader version

1.1.15

### Android version

Android 13

### Other details

Sorry if I reported in wrong way.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rojikku** [comment] 2023-05-08 12:33
Duplicate of #403

**Closed** 2023-05-14 05:44 UTC
Labels: Bug
