### ISSUE TITLE
Source Not Working

### ISSUE THREAD

**Issue by Cuckultry** [LNReader/lnreader-sources#466] opened 2023-03-23 21:11 UTC
### Source information

LightNovelPub

### Steps to reproduce

1.Open Source 
2.Search Something

### Expected behavior

You Should Be Able To Search Something

### Actual behavior

You Get A Json Parse Error

### LNReader version

1.1.14

### Android version

Android 9

### Other details

![Screenshot_20230323-181014_LNReader](https://user-images.githubusercontent.com/128750311/227362459-7e22cd32-f1ae-4d54-ac73-c44760831d3c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-03-24 01:12
Duplicate of #240

**Closed by rajarsheechatterjee** 2023-03-24 01:12 UTC
Labels: Bug
