### ISSUE TITLE
Chapter is Empty

### ISSUE THREAD

**Issue by Fasihurrehman-sys** [LNReader/lnreader-sources#802] opened 2024-02-24 20:39 UTC
### Source information

NovelTop1

### Steps to reproduce

Open LNreader
Open any novel on NovelTop1.
Open any chapter
(Novel should be in library)

### Expected behavior

Content Should be displayed.

### Actual behavior

![Screenshot_2024-02-25-01-35-11-045_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-sources/assets/84008801/011ef6ef-cced-4b62-b732-f5f5d1dee274)

### LNReader version

1.1.19

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-02-26 02:38
Duplicate of #785

**Closed by rajarsheechatterjee** 2024-02-26 02:38 UTC
Labels: Bug
