### ISSUE TITLE
MTLNATION

### ISSUE THREAD

**Issue by discordiy** [LNReader/lnreader-sources#178] opened 2022-02-14 15:34 UTC
### Source name

Mtlnation

### Source link

https://mtlnation.com

### Language

English

### Other details

I hope you add this site to the app, this is the only light novel source which have vast quantity of translated faloo novels.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2022-02-15 03:58
Duplicate of #81

**Closed by rajarsheechatterjee** 2022-02-15 03:58 UTC
Labels: source request
