### ISSUE TITLE
KolNovel bug

### ISSUE THREAD

**Issue by Mingo3347** [LNReader/lnreader-sources#557] opened 2023-08-01 06:27 UTC
### Source information

KolNovel

### Steps to reproduce

1:choose any novel 
2:open any chapter
3:you will find unrelated paragraphs between every sentence

### Expected behavior

Only the content of the novel should be shown and also there is a problem of alot of chapters empty and doesn't work, most of them actually.

### Actual behavior

Unrelated paragraphs 

### LNReader version

1.1.16

### Android version

Android 11

### Other details

![Screenshot_20230801-092717_Email](https://github.com/LNReader/lnreader-sources/assets/108782331/fdf1f5be-74b5-42f4-9243-ef388658ffbc)
This problem was actually fixed before as you can see but it came back after I updated to the latest 1.1.16 version and with the new chapters dropping.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Mingo3347** [comment] 2023-08-04 01:17
I updated to 1.1.17

**Comment by rajarsheechatterjee** [comment] 2023-08-04 03:17
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

**Comment by rajarsheechatterjee** [comment] 2023-09-02 07:10
Duplicate of #534

**Closed by rajarsheechatterjee** 2023-09-02 07:10 UTC
Labels: Bug
