### ISSUE TITLE
Ranobes Domain has changed 

### ISSUE THREAD

**Issue by JJgamerson** [LNReader/lnreader-sources#541] opened 2023-07-15 11:51 UTC
### Source information

Ranobes.net

### Steps to reproduce

Example
1:Open the Source and Webview
2: See the site say "Site is Temporarily DIsabled" with the new domain below
![gjgh](https://github.com/LNReader/lnreader-sources/assets/139627412/2f6e0434-18b7-45b3-b964-3caebe8b92d5)

### Expected behavior

Source to show the site's content

### Actual behavior

The Source leads to a retired domain

### LNReader version

1.1.15

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-07-21 11:36
Duplicate of #540

**Closed by rajarsheechatterjee** 2023-07-21 11:36 UTC
Labels: Bug
