### ISSUE TITLE
Mtlnation source request 

### ISSUE THREAD

**Issue by Adrianjack** [LNReader/lnreader-sources#770] opened 2024-02-12 16:19 UTC
### Source name

Mtlnation 

### Source link

www.mtlnation.com

### Language

English

### Other details

A great mtl website with frequent updates.
It would be great if login to account was possible as mtlnation allows guest account to read only up to 100 chapters. Afterwards the chapters are incomplete.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-02-12 16:20
Duplicate of https://github.com/LNReader/lnreader-sources/issues/81

**Closed by rajarsheechatterjee** 2024-02-12 16:20 UTC
