### ISSUE TITLE
i can´t search in some sources 

### ISSUE THREAD

**Issue by AtreussOT** [LNReader/lnreader-sources#455] opened 2023-02-19 01:27 UTC
### Source information

LightNovelPub

### Steps to reproduce

I should be able to see the covers of the novels when I enter the sources, I should also be able to search for novels from the search engine, but I get an error

### Expected behavior

I should also be able to search for novels from the search engine

### Actual behavior

I get an error

### LNReader version

1.1.14

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-02-19 02:47
Duplicate of #240

**Closed by rajarsheechatterjee** 2023-02-19 02:47 UTC
Labels: Bug
