### ISSUE TITLE
Tanin wo Yosetsukenai Buaisouna Joshi ni Sekkyou shitara, Mechakucha Natsukareta

### ISSUE THREAD

**Issue by installkode** [LNReader/lnreader-sources#506] opened 2023-05-24 11:36 UTC
### Source information

SakuraNovel

### Steps to reproduce

Webview error or webview bug
![Screenshot_2023-05-24-18-07-18-41](https://github.com/LNReader/lnreader-sources/assets/73152491/b678e259-89e1-4660-9f69-72cb0f436fc1)

### Expected behavior

I beg you to fix the webview immediately

### Actual behavior

Not fixed yet 

### LNReader version

1.1.15

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-05-26 09:28
Duplicate of #505

**Closed by rajarsheechatterjee** 2023-05-26 09:28 UTC
Labels: Bug
