### ISSUE TITLE
VOID EVOLUTION SYSTEM

### ISSUE THREAD

**Issue by Dark123405** [LNReader/lnreader-sources#807] opened 2024-02-26 09:28 UTC
The chapter in about 1370+ is all blank when in the WebView there is already chapters in there please fix this
![Screenshot_20240226-172503](https://github.com/LNReader/lnreader-sources/assets/161303690/ef133e7f-4000-4eb2-bb16-9fceede225ae)

**Comment by rajarsheechatterjee** [comment] 2024-02-29 03:30
Duplicate of #785

**Closed by rajarsheechatterjee** 2024-02-29 03:30 UTC
