### ISSUE TITLE
Issue with empty chapter

### ISSUE THREAD

**Issue by Slayerxxx1** [LNReader/lnreader-sources#810] opened 2024-02-26 23:39 UTC
### Source information

Noveltop

### Steps to reproduce

1. I open a chapter in the source
2. It says the chapter is empty
3. I opened web view the chapter is there

### Expected behavior

I expected the chapter to be downloaded so I can read it

### Actual behavior

It's telling me there is no chapter

### LNReader version

1.1.16

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-02-29 03:30
Duplicate of #785

> 1.1.16

Btw the latest app version is _1.1.19_ .

**Closed by rajarsheechatterjee** 2024-02-29 03:30 UTC
Labels: Bug
