### ISSUE TITLE
It Seems Like This Source is not Working anymore

### ISSUE THREAD

**Issue by Sanjounooo** [LNReader/lnreader-sources#148] opened 2022-01-01 06:15 UTC
### Source name

Lightnovelpub

### Source link

https://www.lightnovelpub.com/

### Language

this source is not working anymore. is there a way to fix it? if yes pls fix it (it is ok if not) this is the only source i find easy to use. Thankyou

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2022-01-01 06:24
Duplicate of #133

**Closed by rajarsheechatterjee** 2022-01-01 06:24 UTC
Labels: Source request
