### ISSUE TITLE
I can't read the novel

### ISSUE THREAD

**Issue by Sleepypanda710** [LNReader/lnreader-sources#479] opened 2023-04-13 15:05 UTC
### Source information

Novelmt.com

### Steps to reproduce

I can't read novel that from novelmt.com

### Expected behavior

Everytime i try to read novel from novelmtl.com it always say something like try the webview or report it to githun

### Actual behavior

It should work like every other source

### LNReader version

1.1.14

### Android version

Android 9

### Other details

I hope you can fix this quickly✌

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rojikku** [comment] 2023-05-08 00:07
Probably duplicate of #448

**Closed** 2023-05-08 01:36 UTC
Labels: Bug
