### ISSUE TITLE
Rewayat Ar / Kol novels doesn't working

### ISSUE THREAD

**Issue by ReadMonarch** [LNReader/lnreader-sources#122] opened 2021-11-19 19:49 UTC
### Source information

Rewayat Ar / Kol novels

### Steps to reproduce

.

### Expected behavior

Open

### Actual behavior

No results found

### LNReader version

1.1.7

### Android version

10

### Other details

It's says "no results found"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.6](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2021-12-05 17:20
Duplicate of #118

**Closed by rajarsheechatterjee** 2021-12-05 17:20 UTC
Labels: Bug
