### ISSUE TITLE
Chapter pages are blank

### ISSUE THREAD

**Issue by raycrimso** [LNReader/lnreader-sources#449] opened 2023-02-06 03:30 UTC
### Source information

Readwn.com

### Steps to reproduce

Chapters are not shown
Says report
And thats what I am doing 

### Expected behavior

Chapters pages shouldn't be blank 

### Actual behavior

Chapters are blank

### LNReader version

1.1.13

### Android version

"Android 11"

### Other details

Many novels chapters are blank on readwn.com extension 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-02-06 10:48
Duplicate of #448

**Closed by rajarsheechatterjee** 2023-02-06 10:48 UTC
Labels: Bug
