### ISSUE TITLE
Some novel's in Arnovel source are not working 

### ISSUE THREAD

**Issue by Black7dz** [LNReader/lnreader-sources#553] opened 2023-07-29 15:51 UTC
### Source information

Arnovel 

### Steps to reproduce

![Screenshot_2023-07-29-16-31-49-99_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/140905135/491bc566-3d64-4bc0-ae2b-8bb342a48a8b)

### Expected behavior

There are no chapter's 

### Actual behavior

Instead of no chapter's it will be there a chapter's

### LNReader version

1.1.17

### Android version

Android 13

### Other details

This are some another novel's that are not working
اسبر حريم في نهاية العالم
مشعوذ الدم: مع شريكة سكبوس في نهاية العالم
زوجاتي الثلاث مصاصات دماء جميلات
فن الجسد المهمين النجوم التسعة
الزراعة اون لاين
جينات الإله الخارقة
ذروة فنون القتال
صعود الإمبراطور الكوني
and there is a lot of novel's that are not working,i wish this problem can fixed in the next update because this source are one of the biggest Arabic source's in the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-09-02 06:58
Duplicate of #550

**Closed by rajarsheechatterjee** 2023-09-02 06:58 UTC
Labels: Bug
