### ISSUE TITLE
FastNovel not fetching chapters

### ISSUE THREAD

**Issue by Enrico-Fabbri** [LNReader/lnreader-sources#536] opened 2023-07-09 15:39 UTC
### Source information

FastNovel

### Steps to reproduce

Search a novel from FastNovel source

### Expected behavior

Should load chapters 

### Actual behavior

Not loading chapters

### LNReader version

1.1.15

### Android version

Android 13

### Other details

Ex: https://fastnovel.org/fastnovel/immortal-in-the-magic-world/
![Screenshot_2023-07-09-17-38-31-73_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/70634071/17d60796-7c71-4cce-85ac-dc920f7c4681)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-08-14 07:35
Duplicate of #558

**Closed by rajarsheechatterjee** 2023-08-14 07:35 UTC
Labels: Bug
