### ISSUE TITLE
Kolnovel broken

### ISSUE THREAD

**Issue by ZeuuuuuUS** [LNReader/lnreader-sources#156] opened 2022-01-13 15:21 UTC
### Source information

Kolnovel.com

### Steps to reproduce

This is our most important Arabic website , we all need to fix it Please !

### Actual behavior

.

### LNReader version

1.1.8

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.6](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2022-01-13 15:28
Duplicate of #146 

Currently there's no way for the app to bypass Cloudflare or other scraping prevention services. Feel free to fix it yourself.

**Closed by rajarsheechatterjee** 2022-01-13 15:28 UTC
Labels: Bug
