### ISSUE TITLE
Duplicate chapter after updating library

### ISSUE THREAD

**Issue by Lunaritia** [LNReader/lnreader-sources#731] opened 2024-01-26 18:12 UTC
### Source information

NovelUpdates

### Steps to reproduce

1. Go to update section
2. Scroll down to update
3. Wait
4. Only latest chapter update will be shown

### Expected behavior

Only latest chapter update will be shown

### Actual behavior

![Screenshot_20240127-004535](https://github.com/LNReader/lnreader-sources/assets/157833665/6df414fa-c379-43cc-abdd-e0fb2507b5a5)
![Screenshot_20240127-004551](https://github.com/LNReader/lnreader-sources/assets/157833665/4d0fae05-0f31-4fe5-b37d-f753ed88804b)
![Screenshot_20240127-005007](https://github.com/LNReader/lnreader-sources/assets/157833665/a0ce48b2-e966-451b-b808-a556dc7232e7)

The chapter I've read in the past got updated too (1st SS) and it got duplicated (2nd SS)

And the duplicated ones are considered as new entry, so I need to manually mark them as read so I won't miss which chapter I've read (3rd SS)

### LNReader version

1.1.18

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [ ] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-01-27 02:28
Duplicate of #729

**Closed by rajarsheechatterjee** 2024-01-27 02:28 UTC
Labels: Bug
