### ISSUE TITLE
Chapter is not being displayed 

### ISSUE THREAD

**Issue by ChaosReturn** [LNReader/lnreader-sources#805] opened 2024-02-25 16:23 UTC
### Source information

Noveltop1

### Steps to reproduce

Step 1:Open LN reader app
Step 2:open any novel from noveltop1
Step 3:open any chapter 

### Expected behavior

Should display the chapter of the novel instead of showing chapter empty 

### Actual behavior

Is not displaying the chapter in this website when it shown in other webview

### LNReader version

1.1.15

### Android version

13

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-02-26 02:39
Duplicate of #785

**Closed by rajarsheechatterjee** 2024-02-26 02:39 UTC
Labels: Bug
