### ISSUE TITLE
Ranobes Source New Site

### ISSUE THREAD

**Issue by RobloxSky** [LNReader/lnreader-sources#548] opened 2023-07-26 03:10 UTC
### Source information

Ranobes

### Steps to reproduce

1. First Step:
- When opening ranobes extension it says open source in webview to bypass cloudfare protection.

2. Second Step:
- After clicking on webview it says "The site is temporarily disabled" go to new site "https://ranobes.top"

### Expected behavior

The source should open and show novels but because it changed to another site the previous site which is connected to the lnreader becomes disabled.

### Actual behavior

It always shows canmot bypass cloudfare and on webview it says go to new site

### LNReader version

1.1.17

### Android version

Android 11

### Other details

I think the only problem is to change the site to the new one changing the previous one

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-07-26 03:12
Duplicate of #540

**Closed by rajarsheechatterjee** 2023-07-26 03:12 UTC
Labels: Bug
