### ISSUE TITLE
Request : Faqwiki

### ISSUE THREAD

**Issue by Makuu001** [LNReader/lnreader-sources#789] opened 2024-02-19 07:01 UTC
### Source name

Faqwiki 

### Source link

https://faqwiki.us/

### Language

English

### Other details

amazing website
a lot of completed novels 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment] 2024-02-20 06:49
Duplicate of https://github.com/LNReader/lnreader-sources/issues/619

**Closed by nyagami** 2024-02-20 06:49 UTC
