### ISSUE TITLE
Empty chapter while it's available in WebView 

### ISSUE THREAD

**Issue by NaifES** [LNReader/lnreader-sources#786] opened 2024-02-18 17:26 UTC
### Source information

noveltop1

### Steps to reproduce

Can't downloading empty chapter while it's available in WebView 

### Expected behavior

Should the chapter be downloaded normally 

### Actual behavior

Chapters can't be downloaded.

### LNReader version

1.1.19

### Android version

Android 9

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment] 2024-02-19 18:13
am unable to reproduce, since novelbin extension is the same as noveltop1 you may try that extension?

**Comment by rajarsheechatterjee** [comment] 2024-02-26 02:38
Duplicate of #785

**Closed by rajarsheechatterjee** 2024-02-26 02:38 UTC
Labels: Bug
