### ISSUE TITLE
Tanin wo Yosetsukenai Buaisouna Joshi ni Sekkyou shitara, Mechakucha Natsukareta

### ISSUE THREAD

**Issue by installkode** [LNReader/lnreader-sources#505] opened 2023-05-24 11:15 UTC
### Source information

Sakura Novel

### Steps to reproduce

Webview error 
![Screenshot_2023-05-24-18-07-18-41](https://github.com/LNReader/lnreader-sources/assets/73152491/7a1c3ec8-8662-47bd-b15c-fe60367159c4)

### Expected behavior

Take the right action immediately. Because I open the web normally but the lnreader webview has an error

### Actual behavior

You haven't fixed that bug. I beg to be repaired immediately. To be able to read light novels again

### LNReader version

1.1.15

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-05-26 09:29
Duplicate of #501

**Closed by rajarsheechatterjee** 2023-05-26 09:29 UTC
Labels: Bug
