### ISSUE TITLE
Source issue

### ISSUE THREAD

**Issue by TonyRaj02** [LNReader/lnreader-sources#567] opened 2023-08-14 18:02 UTC
### Source name

FastNovel 

### Source link

https://fastnovel.org/

### Language

English

### Other details

When I tried to update a novel from this source it is showing either cannot read Trim or saying that the app doesn't bypass the source cloudflare..please resolve this issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-08-19 05:24
Duplicate of #558

**Closed by rajarsheechatterjee** 2023-08-19 05:24 UTC
Labels: Source request
