### ISSUE TITLE
Empty chaptera

### ISSUE THREAD

**Issue by bilos125** [LNReader/lnreader-sources#809] opened 2024-02-26 21:58 UTC
### Source information

NovelTop1

### Steps to reproduce

![Screenshot_2024-02-26-23-55-48-799_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-sources/assets/143740937/1b778cf0-2c77-4149-8d2e-94f4e2defc36)

### Expected behavior

Should show the chapter but it is empty

### Actual behavior

It doesnt show the chapters of any novel

### LNReader version

1.1.19

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-02-29 03:28
Duplicate of #785

**Closed by rajarsheechatterjee** 2024-02-29 03:28 UTC
Labels: Bug
