### ISSUE TITLE
Divine Dao Library source doesnt update new chapters even though it is available in webview

### ISSUE THREAD

**Issue by atharvasj780** [LNReader/lnreader-sources#598] opened 2023-09-22 06:52 UTC
### Source information

DivineDaoLibrary

### Steps to reproduce

1. Update library for new chapters with DDL source and updating through pulling down to update in novel.
2. Doesn't add new chapter.

### Expected behavior

adding new chapters from the novel which are visible on the webview

### Actual behavior

no new chapters are added/updated, earlier uninstalling and reinstalling the application used to update the library entry but now it doesn't work anymore 

### LNReader version

1.1.17

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.17](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-09-22 16:22
Duplicate of #598

**Closed by rajarsheechatterjee** 2023-09-22 16:22 UTC
Labels: Bug
