### ISSUE TITLE
Chapter empty in readwn

### ISSUE THREAD

**Issue by Sleepypanda710** [LNReader/lnreader-sources#480] opened 2023-04-13 15:25 UTC
### Source information

Readwn

### Steps to reproduce

![Screenshot_20230413-222222_LNReader](https://user-images.githubusercontent.com/130680466/231807913-d292fc0f-03ae-4a08-8dbf-d49df92cc91c.jpg)

### Expected behavior

![Screenshot_20230413-222222_LNReader](https://user-images.githubusercontent.com/130680466/231808144-e51dcabc-c303-4250-81a7-89bb89ee6c07.jpg)

### Actual behavior

![Screenshot_20230413-222222_LNReader](https://user-images.githubusercontent.com/130680466/231808216-604e25f5-98b8-4586-8354-c3c2dfff8d75.jpg)

### LNReader version

1.1.15

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment] 2023-05-03 19:45
cannot reproduce, please provide chapter URL or novel name

**Comment by Rojikku** [comment] 2023-05-07 23:56
Duplicate of #448

**Closed** 2023-05-08 01:36 UTC
Labels: Bug
