### ISSUE TITLE
All Arabic sites have issues 

### ISSUE THREAD

**Issue by Bokuiio6** [LNReader/lnreader-sources#386] opened 2022-09-05 22:09 UTC
### Source information

Kolnovel

### Steps to reproduce

Idk but pls make any arabic sites available for read novels on app

### Expected behavior

pls make kolnovel or arnovel available to read their novels on the app 

### Actual behavior

Idk

### LNReader version

1.1.13

### Android version

9

### Other details

pls make all arabic sites available to read their novels on the app 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2022-12-09 04:29
Duplicate of #146

**Closed by rajarsheechatterjee** 2022-12-09 04:29 UTC
Labels: Bug
