### ISSUE TITLE
Foxaholic suddenly stopped working

### ISSUE THREAD

**Issue by Sakya22** [LNReader/lnreader-sources#422] opened 2022-11-12 13:57 UTC
### Source information

Foxaholic

### Steps to reproduce

1. Open app
2. Go to Foxaholic

### Expected behavior

All the novels available on Foxaholic should be listed and readable

### Actual behavior

No results found is shown
![Screenshot_2022-11-12-19-25-24-592_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/117186887/201477382-e4878520-9905-425d-b072-74fc2cfe50a0.jpg)

### LNReader version

1.1.13

### Android version

Android 12

### Other details

It was working until yesterday. Now it won't work. And any novels added to my library won't open and say chapter not available

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2022-12-09 04:23
This is due to the website's Cloudflare protection which the app cannot bypass.

Duplicate of #404

**Closed by rajarsheechatterjee** 2022-12-09 04:23 UTC
Labels: Bug, Cloudflare
