### ISSUE TITLE
Issue when opening the chapter it doesn't show but works fine in webview

### ISSUE THREAD

**Issue by MRFool90** [LNReader/lnreader-sources#806] opened 2024-02-25 23:28 UTC
### Source information

Novetop1

### Steps to reproduce

![Screenshot_2024-02-26-07-12-29-83_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/161259510/739c8c3b-ab2b-4db2-88a9-cc8fc01afefa)
![Screenshot_2024-02-26-07-20-39-85_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/LNReader/lnreader-sources/assets/161259510/8a8e1186-e8f3-4863-8e7c-8be7c0a7832f)
By opening the various novel of the said source it loads fine but the chapter doesn't shows up... Its webview works... 

### Expected behavior

This should happen
![Screenshot_2024-02-26-07-23-12-84_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/161259510/fe9e9ac1-d097-466c-b1c6-6ba7248e5cf6)

### Actual behavior

This happened instead
![Screenshot_2024-02-26-07-12-29-83_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/161259510/9272112a-2e8d-4254-a5fa-0a6b97e62eb5)

### LNReader version

1.1.14 and 1.1.19

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-02-26 02:40
Duplicate of #785

**Closed by rajarsheechatterjee** 2024-02-26 02:40 UTC
Labels: Bug
