### ISSUE TITLE
Ar novel websites 

### ISSUE THREAD

**Issue by Guts616** [LNReader/lnreader-sources#323] opened 2022-06-27 01:59 UTC
Rewayat ar  "not working"

Kol novel. "not working"

+
Please add novel paradise site 

Thanks 🤍

**Comment by rajarsheechatterjee** [comment] 2022-06-27 03:54
> Rewayat ar "not working"

They changed their domain and their new website (NovelSpace) is already in the app.

> Kol novel. "not working"

Duplicate of #146 

> Please add novel paradise site

Duplicate of #180

**Closed by rajarsheechatterjee** 2022-06-27 03:54 UTC
