### ISSUE TITLE
meioNovel (source) just show one page

### ISSUE THREAD

**Issue by AhmadNaruto** [LNReader/lnreader-sources#210] opened 2022-04-27 06:38 UTC
on MeioNovel (source indonesia) it only shows one page. I tried to look at the web and there are a lot of novels. 
i tried to look in the sourcecode and in "https://github.com/LNReader/lnreader/tree/main/src/sources/id" MeioNovel does not exist. even though it's in the app.

**Comment by rajarsheechatterjee** [comment] 2022-04-27 06:57
Duplicate of #208

**Closed by rajarsheechatterjee** 2022-04-27 06:57 UTC

**Comment by AhmadNaruto** [comment] 2022-04-29 01:57
> That source is in `multiSrc` as it follows a common template, just need to add total pages for that source in [`MadaraSources.json`](https://github.com/LNReader/lnreader/blob/main/src/sources/multisrc/madara/MadaraSources.json).
> 
> Also open source related issues in the [sources repo](https://github.com/LNReader/lnreader-sources).

totalpage default is 100 right?

**Comment by AhmadNaruto** [comment] 2022-04-29 02:00
![Screenshot_20220429_095859](https://user-images.githubusercontent.com/47007634/165874468-07a8aacf-6caa-499f-b49f-545a2ee5fa05.jpg)

**Comment by rajarsheechatterjee** [comment] 2022-05-02 10:03
> totalpage default is 100 right? but just 12 show in app.

It should be 100. I'll check why it's not working or just add the number of pages.
