### ISSUE TITLE
A problem regarding Kolnovel source (arabic source)

### ISSUE THREAD

**Issue by abdalih4657** [LNReader/lnreader-sources#508] opened 2023-05-25 02:18 UTC
### Source information

Kolnovel

### Steps to reproduce

(I repeated the problem because the problem is still happening)
I have a problem when reading from Kolnovel source. When I click on a chapter it shows some random words between every paragraph.

As in this chapter for example:
![235482734-21a65119-95c3-4412-bbe2-e4ce35a9ad98](https://github.com/LNReader/lnreader-sources/assets/131319764/acb2d3ac-b8e4-464e-a20f-f6e250274bd6)

The yellow lines are the actual text in the original site. But the blue lines are just random words between every paragraph that doesn't make any sense.

This problem is not in the original source.

Here is the same chapter in the original site:
[Classroom of the elite ch 144](https://kolnovel.com/sclassroom-of-the-elitez-195640/)

### Expected behavior

I want to read without these random words between paragraphs

### Actual behavior

(((This problem is with all novels from this source and all chapters)))
I tried some other arabic sources and it was fine.

### LNReader version

1.1.15

### Android version

6.1

### Other details

I can't read from the other sources because I don't find the novels I want there. And also it's annoying to read from the original site because of the ads.

Thanks for your great effort 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-05-26 09:31
Duplicate of #504

**Closed by rajarsheechatterjee** 2023-05-26 09:31 UTC
Labels: Bug
